services:
  # N8N Workflow Automation
  n8n:
    build:
      context: ./n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Sao_Paulo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - n8n_data:/home/node/.n8n
      - ./data/input:/data/input
      - ./data/output:/data/output
      - ./scripts/local:/scripts
    depends_on:
      - postgres

  # PostgreSQL Database
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Streamlit Frontend
  streamlit:
    build: 
      context: ./streamlit
    container_name: streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - ./data/input:/app/data/input
      - ./data/output:/app/data/output
    depends_on:
      - n8n

volumes:
  n8n_data:
  postgres_data:
