name: Release Compiled Executable and Source

on:
  push:
    branches:
      - deploy

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./GREAC
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make the script files executable
        run: chmod +x build.sh

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: "1.11.3"

      - name: Build project
        run: |
          ./build.sh

      - name: Create compiled app tarball
        run: tar -czvf greac.tar.gz greac/

      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v1
        with:
          files: greac.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
